import React, {useState, lazy, Suspense} from 'react';
import {ArrowUpRight, ArrowRight, Check, Layers3, ScanLine, ShieldCheck, FileDown, ChevronDown, Mail, Clock3, CheckCircle2, Circle} from 'lucide-react';
const ArticleMarkdown = lazy(() => import('./ArticleMarkdown'));
import {resources, faqs} from './siteContent';
import cases from './caseStudies.json';

const Arrow = () => <ArrowUpRight size={19} aria-hidden="true"/>;
export function LinkButton({href='/contact',children='Request a free consultation',light=false}) {return <a className={`r-button ${light?'r-button-light':''}`} href={href}>{children}<Arrow/></a>}
const Eyebrow=({children})=><p className="r-eyebrow">{children}</p>;
const Section=({children,className='',id})=><section className={`r-section ${className}`} id={id}><div className="r-container">{children}</div></section>;
const EvidenceNote=()=> <p className="r-evidence">Anonymised Heutrix delivery for one Australian disability support provider. These 15 stories describe one connected body of work, not 15 clients. Approximate outcomes are client-feedback supported or structural estimates, not independently audited results or promises.</p>;
const featured=[cases[2],cases[5],cases[8]];
const cardTitles=['Onboarding with a clear finish line','Reminders that carry the next action','Reconciliation with the evidence in view'];
const cardStats=['1–4 hours','≈60%','Up to ≈2 hours'];
const cardUnits=['less administration per worker','fewer out-of-cycle payment events','saved per discrepancy'];
export function CaseCards(){return <div className="r-case-grid">{featured.map((c,i)=><a key={c.slug} href={'/case-studies/'+c.slug} className="r-case-card"><div className="r-case-top"><span>{c.category}</span><Arrow/></div><div className="r-stat">{cardStats[i]}</div><p className="r-stat-unit">{cardUnits[i]}</p><h3>{cardTitles[i]}</h3><p className="r-small">Approximate result supported by client feedback. Read the evidence and limits.</p><span className="r-text-link">Read the case study <ArrowRight size={17}/></span></a>)}</div>}
function WorkflowView(){const [stage,setStage]=useState('Intake');const data={Intake:[['Enquiry received','Intake lead','Confirm next step'],['Documents requested','Coordinator','Follow up on missing item'],['Ready for review','Service lead','Review commencement']],Onboarding:[['Access requested','Admin lead','Confirm permissions'],['Invitation accepted','Team lead','Check usable access'],['Handover ready','Supervisor','Confirm completion']],Reporting:[['Inputs requested','Report owner','Check missing inputs'],['Exceptions flagged','Operations lead','Resolve discrepancy'],['Ready for review','Manager','Review and sign off']]};return <div className="r-workflow"><div className="r-workflow-head"><span><Layers3 size={17}/> A clearer working day</span><span className="r-live">Illustrative view</span></div><div className="r-tabs" aria-label="Example workflow">{Object.keys(data).map(t=><button key={t} type="button" aria-pressed={t===stage} onClick={()=>setStage(t)}>{t}</button>)}</div><div className="r-workflow-labels"><span>Work in progress</span><span>Owner / next action</span></div>{data[stage].map((r,i)=><div className="r-workflow-row" key={r[0]}><span className={'r-step-icon step-'+i}>{i===2?<CheckCircle2 size={18}/>:<Circle size={18}/>}</span><strong>{r[0]}</strong><div><span>{r[1]}</span><small>{r[2]}</small></div></div>)}<p className="r-demo-note">Synthetic example · no client or participant records</p></div>}
export function RefinedHome(){return <div className="r-page">
<section className="r-hero"><div className="r-container r-hero-grid"><div className="r-hero-copy"><Eyebrow>Workflow first. Technology second.</Eyebrow><h1>Less chasing.<br/>Clearer work.<br/><span>More room to care.</span></h1><p className="r-lead">Practical workflow improvement for Australian disability support providers and selected allied health practices.</p><p className="r-hero-description">Turn scattered follow-ups, handovers and spreadsheets into a clearer way of working—one operational workflow at a time.</p><div className="r-actions"><LinkButton/><a href="/services" className="r-text-link">Explore our services <ArrowRight size={18}/></a></div><p className="r-micro"><Clock3 size={14}/> 20 minutes · free · no obligation</p></div><div className="r-hero-visual"><img className="r-hero-photo" src="/images/workflow-team.webp" alt="Illustrative scene of two operations colleagues planning a workflow together" width="1536" height="1024" fetchPriority="high"/><div className="r-photo-label">Illustrative AI-generated image</div><WorkflowView/></div></div></section>
<div className="r-principles"><div className="r-container"><span>Built around the work your team actually does.</span><span><Check size={16}/> Clear ownership</span><span><Check size={16}/> Human judgement</span><span><Check size={16}/> Maintainable handover</span></div></div>
<Section className="r-problem"><div className="r-section-heading"><div><Eyebrow>The work between the systems</Eyebrow><h2>Good people.<br/>Too many loose ends.</h2></div><p>Your team knows what needs doing. The challenge is seeing who owns it, what is waiting and what happens next.</p></div><div className="r-problem-grid">{[['01','The follow-up lives in someone’s inbox.','Enquiries, missing documents and reminders rely on individual memory.'],['02','The handover has no clear finish line.','Tasks look complete before access, checks or the next owner are ready.'],['03','The report starts with a search.','Managers reconstruct the picture from spreadsheets, folders and conversations.']].map(x=><div key={x[0]}><span className="r-number">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Section>
<Section className="r-services"><div className="r-section-heading"><div><Eyebrow>Three ways forward</Eyebrow><h2>The right next step.<br/>A scope you can see.</h2></div><a className="r-text-link" href="/services">Compare all services <Arrow/></a></div><div className="r-service-grid"><a className="r-service-card" href="/services#heutrix-diagnostics"><ScanLine size={28}/><span className="r-service-label">When the priority is unclear</span><h3>Heutrix<br/>Diagnostics</h3><p>Find the workflow worth improving, understand the constraints and decide what to do next—including when not to build.</p><span className="r-service-bottom">Get a decision-ready brief <Arrow/></span></a><a className="r-service-card r-service-primary" href="/services#heutrix-workflow-transformation"><div className="r-service-icon"><Layers3 size={28}/><span>From process to practice</span></div><span className="r-service-label">When one workflow is ready to change</span><h3>Heutrix Workflow<br/>Transformation</h3><p>Redesign, build and test one operational workflow. Give your team clear ownership, practical guidance and a system they can use.</p><span className="r-service-bottom">Turn a workflow into a working system <Arrow/></span></a><a className="r-service-card" href="/ai-guardrails"><ShieldCheck size={28}/><span className="r-service-label">When AI needs practical boundaries</span><h3>Heutrix<br/>AI Guardrails</h3><p>Give staff clear rules for appropriate AI use, information boundaries, human review and escalation.</p><span className="r-service-bottom">Make the rules usable <Arrow/></span></a></div></Section>
<Section className="r-proof"><div className="r-section-heading"><div><Eyebrow>From Heutrix delivery</Eyebrow><h2>Small workflow details.<br/>Meaningful operating change.</h2></div><a className="r-text-link" href="/case-studies">Explore the case studies <Arrow/></a></div><CaseCards/><EvidenceNote/></Section>
<FounderIntro/>
<Section className="r-method" id="heutrix-method"><div className="r-method-grid"><div><Eyebrow>Our four-step approach</Eyebrow><h2>The Heutrix<br/><span>Method.</span></h2><p>Understand the problem. Prioritise what matters. Build the right improvement and leave your team ready to use it.</p><p>We start with the workflow. The right next step may be a process change, a scoped build or a no-build recommendation.</p><LinkButton href="/about" light>Why Heutrix</LinkButton></div><ol className="r-method-list">{[['Diagnostics','Understand the operational problem, map how work happens and identify the gaps. A standalone Heutrix Diagnostics engagement is useful when the priority or feasible solution is unclear.'],['Triage','Prioritise the bottlenecks, dependencies and risks. Agree one useful next step, a clear scope and what success must look like.'],['Automation','Implement the simplest suitable improvement, using automation where it helps. Test the workflow, permissions and exception paths, with accountable human review.'],['Handover','Guide the team, document the workflow and agree ownership, maintenance and support boundaries so the solution is usable after handover.']].map((s,i)=><li key={s[0]}><span>0{i+1}</span><div><h3>{s[0]}</h3><p>{s[1]}</p></div></li>)}</ol></div></Section>
<Section className="r-resources"><div className="r-section-heading"><div><Eyebrow>A useful place to start</Eyebrow><h2>Make your next decision<br/>a little clearer.</h2></div><p>Three practical tools. Ready to use.<br/>No email address required.</p></div><div className="r-resource-grid">{resources.map((r,i)=><article className="r-resource-card" key={r.id}><a className={'r-resource-cover resource-'+i} href={r.guideHref}><img src={'/images/resource-'+i+'.webp'} alt={r.title+' PDF guide cover'} loading="lazy" width="400" height="566"/></a><span className="r-small r-resource-type">PDF GUIDE + EXCEL WORKBOOK</span><h3>{r.title}</h3><p>{['Find the recurring workflow that deserves attention first.','Make one intake or commencement path visible.','Give administrative AI use a practical review path.'][i]}</p><div className="r-download-links"><a href={r.guideHref} download><FileDown size={17}/> PDF guide</a><a href={r.workbookHref} download><FileDown size={17}/> Workbook</a></div></article>)}</div><p className="r-evidence">General operational starter tools, not tailored advice, approved workflows or assurances of compliance. Use synthetic or appropriately de-identified information in approved systems.</p></Section>
<Section className="r-audiences"><Eyebrow>Who we help</Eyebrow><div className="r-audience-grid"><a href="/disability-providers"><span>Our primary focus</span><h2>Disability support<br/>providers.</h2><p>Intake, worker onboarding, service commencement, document tracking and operational handovers.</p><span className="r-text-link">Explore provider workflows <Arrow/></span></a><a href="/allied-health"><span>For selected practices</span><h2>Allied health<br/>teams.</h2><p>Referral follow-up, document collection, reporting preparation and practice visibility.</p><span className="r-text-link">Explore practice workflows <Arrow/></span></a></div></Section>
<Section className="r-faq"><div className="r-faq-grid"><div><Eyebrow>A few things worth knowing</Eyebrow><h2>Start with clarity.</h2><a className="r-text-link" href="/faq">More questions answered <Arrow/></a></div><div>{[['Do we need to know which service we need?','No. Bring one high-level operational problem to the free consultation. We can discuss whether Diagnostics, Workflow Transformation or AI Guardrails is a useful next step—or whether Heutrix is not the right fit.'],['Will this replace our existing systems?','Not necessarily. We look at your approved existing systems first. Any new tool, integration or replacement depends on feasibility and the agreed scope.'],['What happens after the consultation?','If there is a fit, paid work is agreed in writing before it begins: deliverables, responsibilities, timing, acceptance criteria and the applicable fee. The consultation does not commit you to a project.'],['Can we share participant or patient information?','Please keep enquiries general. Do not send participant, patient, worker, health, payment or other sensitive information. Project data arrangements are agreed separately before real information is accepted.']].map(x=><details key={x[0]}><summary>{x[0]}<ChevronDown size={18}/></summary><p>{x[1]}</p></details>)}</div></div></Section>
<FinalCta/></div>}
export function FinalCta(){return <Section className="r-final"><Eyebrow>One workflow is a good place to start</Eyebrow><h2>What keeps your team<br/>chasing updates?</h2><p>Let’s talk about it. A free, 20-minute conversation to work out a practical next step.</p><LinkButton light/><p className="r-micro">No obligation. No sensitive information needed.</p></Section>}
export function CaseStudiesPage(){const [filter,setFilter]=useState('All');const filtered=cases.filter(c=>filter==='All'||c.category===filter);return <div className="r-page"><Section className="r-page-hero"><Eyebrow>Heutrix delivery / Case studies</Eyebrow><h1>Better workflows,<br/><span>in the details.</span></h1><p className="r-lead">A closer look at the operating problems, decisions and practical systems behind one connected body of Heutrix delivery.</p><EvidenceNote/></Section><Section className="r-proof"><CaseCards/></Section><Section><div className="r-filter" aria-label="Filter case studies">{['All','Onboarding','Financial operations','Incident management & shift notes'].map(c=><button key={c} aria-pressed={c===filter} onClick={()=>setFilter(c)}>{c}</button>)}</div><p className="r-small" aria-live="polite">{filtered.length} case studies</p><div className="r-case-list">{filtered.map(c=><a href={'/case-studies/'+c.slug} key={c.slug}><span className="r-number">{String(c.number).padStart(2,'0')}</span><div><span className="r-small">{c.category}</span><h2>{c.title}</h2></div><Arrow/></a>)}</div></Section><FinalCta/></div>}
export function CaseStudyPage({slug}){const c=cases.find(c=>c.slug===slug);if(!c)return <Section><h1>Case study not found</h1><a href="/case-studies">View case studies</a></Section>;return <div className="r-page"><Section className="r-page-hero r-article-hero"><a href="/case-studies" className="r-text-link">← All case studies</a><Eyebrow>{c.category} / Anonymised Heutrix delivery</Eyebrow><h1>{c.title}</h1><EvidenceNote/></Section><Section><article className="r-article"><Suspense fallback={<p>Loading case study…</p>}><ArticleMarkdown body={c.body}/></Suspense></article></Section><FinalCta/></div>}
export function ConsultationPage(){const [copied,setCopied]=useState(false);const email='hello@heutrix.com.au';const subject=encodeURIComponent('Free consultation request');const body=encodeURIComponent('Hello Heutrix,\n\nI would like to arrange a free 20-minute consultation.\n\nOrganisation:\nMy role:\nOne operational workflow we would like to improve (high-level only):\nPreferred days/times and time zone:\n\n');async function copy(){try{await navigator.clipboard.writeText(email);setCopied(true)}catch{setCopied('blocked')}}return <div className="r-page"><Section className="r-page-hero"><div className="r-contact-grid"><div><Eyebrow>A clearer next step</Eyebrow><h1>Let’s talk about<br/><span>the work.</span></h1><p className="r-lead">Request a free consultation.</p><p>Twenty minutes to discuss one operational problem and whether Heutrix is the right fit to help.</p><ul className="r-contact-points"><li><Check/> No obligation to start a project</li><li><Check/> No need to choose a service first</li><li><Check/> A useful next step—even if it is not a build</li></ul></div><div className="r-contact-card"><Mail size={28}/><h2>Start a conversation.</h2><p>Email a general description of the workflow and a few suitable times. We’ll agree a time with you by email.</p><a className="r-contact-email" href={'mailto:'+email}>{email}</a><LinkButton href={`mailto:${email}?subject=${subject}&body=${body}`}>Email your consultation request</LinkButton><p className="r-small">Opens your email app with a draft. Review and send it there. This is a request, not a confirmed booking.</p><button className="r-copy" onClick={copy}>{copied===true?'Email address copied':'Copy email address'}</button><p className="r-small" role="status">{copied===true?'Email address copied to clipboard.':copied==='blocked'?'Your browser could not copy it. Select and copy hello@heutrix.com.au above.':''}</p><div className="r-privacy-note"><ShieldCheck size={21}/><p>Please do not include participant, patient, worker, clinical, payment, credential or other sensitive information.</p></div></div></div></Section><Section className="r-services"><div className="r-section-heading"><h2>What happens next?</h2><p>The conversation is a fit check, not a consulting workshop or tailored professional advice.</p></div><div className="r-problem-grid">{[['01','Describe the friction','Share one recurring operational issue at a high level.'],['02','Talk through the fit','We discuss the workflow, its boundaries and the next decision.'],['03','Agree the next step','Any paid work has a written scope and fee before it begins.']].map(x=><div key={x[0]}><span className="r-number">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Section></div>}

export function FounderIntro(){return <Section className="r-origin"><div className="r-origin-grid"><div><Eyebrow>Why Heutrix exists</Eyebrow><h2>Better workflows begin<br/>with lived experience.</h2></div><div><p className="r-lead">Heutrix grew from first-hand experience running a disability and allied health services organisation.</p><p>We brought that operational experience together with project delivery, workflow implementation, data and engineering to help teams carry work through—from the first action to a clear handover.</p><a className="r-text-link" href="/about">Read the Heutrix story <Arrow/></a></div></div></Section>}
const deliveryStories=[
 {label:'Worker onboarding',title:'An invitation is only the beginning.',before:'Creating a user account could be mistaken for completed onboarding.',after:'The workflow carried through to accepted access, the right groups and a configured invoice handover.',steps:['Create access','Send invitation','Check acceptance','Prepare handover'],caseIndex:2},
 {label:'Payment reminders',title:'Put the next action in the reminder.',before:'A generic reminder still left workers searching for the correct file, tab and instructions.',after:'A configured workbook, dedicated link and end-of-cycle reminder gave workers a clear place to act.',steps:['Prepare workbook','Provide direct link','Send reminder','Guide completion'],caseIndex:5},
 {label:'Action follow-up',title:'Give each action somewhere to go.',before:'Follow-up actions could get lost in meeting notes or broad recommendations.',after:'Actions, responsibility, completion dates and review were brought into a visible follow-up path.',steps:['Record action','Assign owner','Set due date','Review and close'],caseIndex:12}
];
export function DeliveryStory(){const [selected,setSelected]=useState(0);const story=deliveryStories[selected];return <Section className="r-delivery-story"><div className="r-section-heading"><div><Eyebrow>Inside the work</Eyebrow><h2>The difference is<br/>in the follow-through.</h2></div><p>Explore three practical changes from our work with one Australian disability support provider.</p></div><div className="r-story-switch" aria-label="Explore a delivery story">{deliveryStories.map((s,i)=><button key={s.label} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{s.label}</button>)}</div><div className="r-story-panel" aria-live="polite"><h3>{story.title}</h3><ol className="r-story-path">{story.steps.map((step,i)=><li key={step}><span>0{i+1}</span><strong>{step}</strong>{i<3&&<ArrowRight aria-hidden="true"/>}</li>)}</ol><div className="r-story-change"><div><span className="r-story-label">The friction</span><p>{story.before}</p></div><div><span className="r-story-label">The change</span><p>{story.after}</p></div></div><a className="r-text-link" href={'/case-studies/'+cases[story.caseIndex].slug}>Read the full story and evidence <Arrow/></a><p className="r-small r-story-caption">Simplified diagram of the delivery approach. Each case study explains the scope and evidence limits.</p></div></Section>}
export function RefinedAbout(){return <div className="r-page">
<Section className="r-page-hero"><Eyebrow>The Heutrix story</Eyebrow><h1>We started inside<br/><span>the work.</span></h1><p className="r-lead">Heutrix grew from first-hand experience running a disability and allied health services organisation—and a practical question: how can the work behind care run more clearly?</p><div className="r-origin-grid r-about-intro"><p>In provider operations, a task rarely ends with one person. An enquiry needs a next step. A new worker needs usable access. A payment query needs the right information. Between each action is a handover that someone has to carry through.</p><p>That perspective shaped Heutrix. We focus on the everyday details that make a process work: clear ownership, information people can find and a shared understanding of what “finished” means.</p></div></Section>
<Section className="r-origin"><div className="r-origin-grid"><div><Eyebrow>Experience brought together</Eyebrow><h2>From understanding<br/>the pressure to<br/>improving the process.</h2></div><div><p className="r-lead">Our founding team brings together provider administration and operations, project delivery, workflow implementation, data and analytics, and backend engineering and infrastructure.</p><p>Those experiences meet in one approach: understand the people doing the work, trace where the process becomes difficult and build an improvement the team can use.</p><p>Our delivery stories show what that looks like in practice. Worker onboarding carries through to accepted access. Reminders include a clear place to act. Follow-up actions have an owner and a review path. Each change addresses a specific point where work can stall.</p><p>Today, we help Australian disability support providers and selected allied health practices improve one workflow at a time, with the same principle that shaped Heutrix from the start: workflow first, technology second.</p></div></div></Section>
<DeliveryStory/><Section><div className="r-origin-grid"><div><Eyebrow>How the story shapes our work</Eyebrow><h2>A clearer process.<br/>A usable handover.</h2></div><div><p>We map how work happens, agree the improvement, test it with the people who use it and document how to keep it running. Sometimes the right answer is a process change. Sometimes it is a carefully scoped build.</p><p>Clinical decisions and other accountable judgements stay with the appropriate people. Scope, responsibilities and support arrangements are agreed before paid work begins.</p><a href="/#heutrix-method" className="r-text-link">Explore the four-step Heutrix Method <Arrow/></a></div></div></Section><FinalCta/></div>}
