import React, {useState, lazy, Suspense} from 'react';
import {ArrowUpRight, ArrowRight, Check, Layers3, ScanLine, ShieldCheck, FileDown, ChevronDown, Mail, Clock3, CheckCircle2, Circle} from 'lucide-react';
const ArticleMarkdown = lazy(() => import('./ArticleMarkdown'));
import {faqs} from './siteContent';
import cases from './caseStudies.json';
import WorkflowPressurePoints from './components/WorkflowPressurePoints';
import {homeOffers, homeMethod, homeWhy, homeEngagement, homeCapabilities, homeFaqs} from './homepageContent';

const Arrow = () => <ArrowUpRight size={19} aria-hidden="true"/>;
export function LinkButton({href='/contact',children='Talk to Heutrix',light=false}) {return <a className={`r-button ${light?'r-button-light':''}`} href={href}>{children}<Arrow/></a>}
const Eyebrow=({children})=><p className="r-eyebrow">{children}</p>;
const Section=({children,className='',id})=><section className={`r-section ${className}`} id={id}><div className="r-container">{children}</div></section>;
const EvidenceNote=()=> <p className="r-evidence">Illustrative workflow examples. These explain possible approaches, not verified client projects or promised results.</p>;
const featured=cases;
const cardTitles=cases.map(c=>c.title);
const cardStats=['Clear starts','Useful reminders','Visible actions'];
const cardUnits=['Define what ready means','Make the next step easy to find','Assign ownership and review'];
export function CaseCards(){return <div className="r-case-grid">{featured.map((c,i)=><a key={c.slug} href={'/case-studies/'+c.slug} className="r-case-card"><div className="r-case-top"><span>{c.category}</span><Arrow/></div><div className="r-stat">{cardStats[i]}</div><p className="r-stat-unit">{cardUnits[i]}</p><h3>{cardTitles[i]}</h3><p className="r-small">A possible improvement to explore around your existing systems.</p><span className="r-text-link">Explore the workflow <ArrowRight size={17}/></span></a>)}</div>}
function WorkflowView(){const [stage,setStage]=useState('Intake');const data={Intake:[['Enquiry received','Intake lead','Confirm next step'],['Documents requested','Coordinator','Follow up on missing item'],['Ready for review','Service lead','Review commencement']],Onboarding:[['Access requested','Admin lead','Confirm permissions'],['Invitation accepted','Team lead','Check usable access'],['Handover ready','Supervisor','Confirm completion']],Reporting:[['Inputs requested','Report owner','Check missing inputs'],['Exceptions flagged','Operations lead','Resolve discrepancy'],['Ready for review','Manager','Review and sign off']]};return <div className="r-workflow"><div className="r-workflow-head"><span><Layers3 size={17}/> A clearer working day</span><span className="r-live">Illustrative view</span></div><div className="r-tabs" aria-label="Example workflow">{Object.keys(data).map(t=><button key={t} type="button" aria-pressed={t===stage} onClick={()=>setStage(t)}>{t}</button>)}</div><div className="r-workflow-labels"><span>Work in progress</span><span>Owner / next action</span></div>{data[stage].map((r,i)=><div className="r-workflow-row" key={r[0]}><span className={'r-step-icon step-'+i}>{i===2?<CheckCircle2 size={18}/>:<Circle size={18}/>}</span><strong>{r[0]}</strong><div><span>{r[1]}</span><small>{r[2]}</small></div></div>)}<p className="r-demo-note">Synthetic example · no client or participant records</p></div>}
export function RefinedHome(){return <div className="r-page r-home">
  <section className="r-hero"><div className="r-container r-hero-grid">
    <div className="r-hero-copy"><Eyebrow>Operational improvement for disability service providers</Eyebrow>
      <h1>Build a disability service business that <span>runs better as it grows.</span></h1>
      <p className="r-lead">Heutrix helps Australian disability service providers, including NDIS providers, improve the non-clinical workflows around their existing systems — with clearer ownership, less administrative friction and better visibility as the organisation grows.</p>
      <div className="r-actions"><LinkButton/><a href="/#heutrix-method" className="r-text-link">See How It Works <ArrowRight size={18} aria-hidden="true"/></a></div>
      <p className="r-micro"><Clock3 size={14} aria-hidden="true"/>Start with a free 20-minute introductory conversation. No obligation.</p>
    </div>
    <div className="r-hero-visual"><img className="r-hero-photo" src="/images/workflow-team.webp" alt="Illustrative scene of two operations colleagues planning a workflow together" width="1536" height="1024" fetchPriority="high"/><div className="r-photo-label">Illustrative AI-generated image</div><WorkflowView/></div>
  </div></section>
  <WorkflowPressurePoints/>
  <Section className="r-services" id="home-offers">
    <div className="r-section-heading"><div><Eyebrow>How Heutrix helps</Eyebrow><h2>Start with the problem you need to solve.</h2></div></div>
    <p className="home-intro">Whether you need clarity on what is slowing the organisation down, improvements to a specific workflow, or stronger controls around AI use, Heutrix provides a clear path forward.</p>
    <div className="r-service-grid">{homeOffers.map((offer,i)=>{const Icon=[ScanLine,Layers3,ShieldCheck][i];return <article key={offer.title} className={`r-service-card ${i===1?'r-service-primary':''}`}>
      <Icon size={28} aria-hidden="true"/><h3>{offer.title}</h3><p className="home-offer-headline">{offer.headline}</p><p>{offer.body}</p>
      <a className="r-service-bottom" href={offer.href}>{offer.cta}<Arrow/></a>
    </article>})}</div>
    <p className="home-offer-boundary">Three independent entry points. When the workflow and dependencies are clear, you can start directly with Workflow Transformation. AI Guardrails can also be engaged directly.</p>
    <a className="r-text-link" href="/services">Explore Services <Arrow/></a>
    <p className="r-micro">Not sure where to begin? The introductory conversation can help determine the appropriate next step.</p>
  </Section>
  <Section className="r-method" id="heutrix-method"><div className="r-method-grid">
    <div><Eyebrow>Workflow first</Eyebrow><h2>Improve the workflow before choosing the solution.</h2><p>Heutrix starts by understanding how work moves through your organisation — the people, decisions, information and points where work slows down. The next step may be a simpler process, a scoped implementation or a recommendation not to build.</p><LinkButton href="/about" light>See How We Help</LinkButton><p className="home-method-note">Technology supports the solution. It does not define the problem.</p></div>
    <ol className="r-method-list">{homeMethod.map(([title,body],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol>
  </div></Section>
  <Section className="r-proof" id="home-proof"><div className="r-section-heading"><div><Eyebrow>In practice</Eyebrow><h2>A clearer way to investigate reporting discrepancies.</h2></div></div>
    <article className="r-case-card home-featured-proof"><div><h3>Bringing invoices and time records into one review workflow</h3><p>An Australian disability support provider reviewed contractor invoices and QuickBooks time records in separate sources. Heutrix aligned the reporting model and delivered a cloud-connected Power BI reconciliation report so reviewers could filter the same information and investigate differences in one place. Client feedback supported approximately 1–2 hours less reconciliation and investigation effort per discrepancy.</p><a className="r-text-link" href="/services#heutrix-workflow-transformation">View Transformations <Arrow/></a></div>
    <aside className="home-proof-note"><p className="r-evidence">Anonymised Heutrix delivery. The approximate efficiency range is supported by client feedback, not an audited time study. It is not a promise of future results.</p></aside></article>
  </Section>
  <Section className="home-why" id="home-why"><Eyebrow>Why Heutrix</Eyebrow><h2>Operational improvement built around how your organisation actually works.</h2><p className="home-intro">Disability service providers do not need more technology for its own sake. They need workflows that are easier to operate, easier to understand and better equipped to support growth.</p>
    <div className="r-problem-grid home-four-grid">{homeWhy.map(([title,body])=><div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div>
  </Section>
  <Section className="home-engagement" id="home-engagement"><div className="r-method-grid"><div><Eyebrow>What happens next</Eyebrow><h2>A clear path from conversation to improvement.</h2><p>You do not need to know which Heutrix service you need before getting in touch.</p></div>
    <ol className="r-method-list">{homeEngagement.map(([title,body,note],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p>{note&&<p className="home-step-note">{note}</p>}</div></li>)}</ol>
    </div><div className="r-actions"><LinkButton/></div><p className="r-micro">Free 20-minute introductory conversation · No obligation · Diagnostics are quoted separately.</p>
  </Section>
  <Section className="r-resources" id="home-scorecard"><div className="home-scorecard-grid"><div><Eyebrow>Free workflow scorecard</Eyebrow><h2>Where is operational friction slowing you down?</h2><p>Use the online Workflow Bottleneck Scorecard to assess one recurring non-clinical workflow. Review the friction, evidence, feasibility and control questions, then get a practical next step to discuss with your team.</p>
    <ul className="home-resource-points"><li>Review manual effort, handovers, delay, rework and visibility.</li><li>Check how strong the evidence is and whether a change is feasible.</li><li>Identify control questions that need attention before implementation.</li><li>Save an action plan or discuss the selected result with Heutrix.</li></ul>
    </div><div className="r-resource-card home-scorecard-action"><h3>Workflow Bottleneck Scorecard</h3><p>The online assessment checks one workflow. To compare up to 12 workflows, use the downloadable scorecard workbook.</p><LinkButton href="/resources/workflow-bottleneck-scorecard">Get the Scorecard</LinkButton>
    <div className="r-download-links"><a href="/downloads/workflow-bottleneck-scorecard-guide.pdf" download><FileDown size={17} aria-hidden="true"/>Get the Guide</a><a href="/downloads/workflow-bottleneck-scorecard.xlsx" download><FileDown size={17} aria-hidden="true"/>Get the Template</a></div>
    <p className="r-micro">Free · No email address required · No consultation required</p><p className="r-evidence">A general starting point, not a paid Diagnostic or approval to implement a change. Keep information general and non-sensitive.</p></div></div>
  </Section>
  <FounderIntro homepage/>
  <Section className="r-faq" id="home-faq"><div className="r-faq-grid"><div><Eyebrow>Common questions</Eyebrow><h2>Before you talk to Heutrix.</h2></div><div>{homeFaqs.map(([question,answer])=><details key={question}><summary>{question}<ChevronDown size={18} aria-hidden="true"/></summary>{answer.split('\n\n').map(p=><p key={p}>{p}</p>)}</details>)}</div></div><div className="r-actions"><LinkButton/></div><p className="r-micro">Start with a free 20-minute introductory conversation.</p></Section>
  <FinalCta homepage/>
</div>}
export function FinalCta({homepage=false}){if(homepage)return <Section className="r-final" id="home-final"><Eyebrow>Start with a conversation</Eyebrow><h2>What could work better in your organisation?</h2><p>If manual processes, disconnected workflows or limited operational visibility are making your organisation harder to run, start by showing us where the friction is.</p><p>We will use a free 20-minute introductory conversation to understand the situation and determine whether Heutrix can help.</p><div className="r-actions"><LinkButton light/><a className="r-text-link" href="/resources/workflow-bottleneck-scorecard">Get the Scorecard <Arrow/></a></div><p className="r-micro">Free 20-minute introductory conversation · No obligation · Heutrix Diagnostics is a separate paid engagement.</p><p className="r-evidence home-handoff">The contact page helps you prepare an email request. Review and send it in your email app; a time is then agreed separately.</p></Section>;return <Section className="r-final"><Eyebrow>One workflow is a good place to start</Eyebrow><h2>What keeps your team<br/>chasing updates?</h2><p>Let’s talk about it. A free, 20-minute conversation to work out a practical next step.</p><LinkButton light/><p className="r-micro">No obligation. No sensitive information needed.</p></Section>}
export function CaseStudiesPage(){const [filter,setFilter]=useState('All');const filtered=cases.filter(c=>filter==='All'||c.category===filter);return <div className="r-page"><Section className="r-page-hero"><Eyebrow>Workflow examples</Eyebrow><h1>Better workflows,<br/><span>in the details.</span></h1><p className="r-lead">Explore how clearer ownership, practical checks and useful handovers could improve everyday provider workflows.</p><EvidenceNote/></Section><Section className="r-proof"><CaseCards/></Section><Section><div className="r-filter" aria-label="Filter workflow examples">{['All','Onboarding','Financial operations','Incident management & shift notes'].map(c=><button key={c} aria-pressed={c===filter} onClick={()=>setFilter(c)}>{c}</button>)}</div><p className="r-small" aria-live="polite">{filtered.length} workflow examples</p><div className="r-case-list">{filtered.map(c=><a href={'/case-studies/'+c.slug} key={c.slug}><span className="r-number">{String(c.number).padStart(2,'0')}</span><div><span className="r-small">{c.category}</span><h2>{c.title}</h2></div><Arrow/></a>)}</div></Section><FinalCta/></div>}
export function CaseStudyPage({slug}){const c=cases.find(c=>c.slug===slug);if(!c)return <Section><h1>Case study not found</h1><a href="/case-studies">View case studies</a></Section>;return <div className="r-page"><Section className="r-page-hero r-article-hero"><a href="/case-studies" className="r-text-link">← All workflow examples</a><Eyebrow>{c.category} / Illustrative workflow example</Eyebrow><h1>{c.title}</h1><EvidenceNote/></Section><Section><article className="r-article"><Suspense fallback={<p>Loading workflow example…</p>}><ArticleMarkdown body={c.body}/></Suspense></article></Section><FinalCta/></div>}
export function ConsultationPage(){const [copied,setCopied]=useState(false);const email='hello@heutrix.com.au';const subject=encodeURIComponent('20-minute introductory conversation');const body=encodeURIComponent('Hello Heutrix,\n\nI would like to arrange a 20-minute introductory conversation.\n\nOrganisation:\nMy role:\nOne operational workflow we would like to improve (high-level only):\nPreferred days/times and time zone:\n\n');async function copy(){try{await navigator.clipboard.writeText(email);setCopied(true)}catch{setCopied('blocked')}}return <div className="r-page"><Section className="r-page-hero"><div className="r-contact-grid"><div><Eyebrow>A clearer next step</Eyebrow><h1>Let’s talk about<br/><span>the work.</span></h1><p className="r-lead">Talk to Heutrix.</p><p>Twenty minutes to discuss one operational problem and whether Heutrix is the right fit to help.</p><ul className="r-contact-points"><li><Check/> No obligation to start a project</li><li><Check/> No need to choose a service first</li><li><Check/> A useful next step—even if it is not a build</li></ul></div><div className="r-contact-card"><Mail size={28}/><h2>Start a conversation.</h2><p>Email a general description of the workflow and a few suitable times. We’ll agree a time with you by email.</p><a className="r-contact-email" href={'mailto:'+email}>{email}</a><LinkButton href={`mailto:${email}?subject=${subject}&body=${body}`}>Open Email Draft</LinkButton><p className="r-small">Opens your email app with a draft. Review and send it there. This is a request, not a confirmed booking.</p><button className="r-copy" onClick={copy}>{copied===true?'Email address copied':'Copy email address'}</button><p className="r-small" role="status">{copied===true?'Email address copied to clipboard.':copied==='blocked'?'Your browser could not copy it. Select and copy hello@heutrix.com.au above.':''}</p><div className="r-privacy-note"><ShieldCheck size={21}/><p>Please do not include participant, patient, worker, clinical, payment, credential or other sensitive information.</p></div></div></div></Section><Section className="r-services"><div className="r-section-heading"><h2>What happens next?</h2><p>The conversation is a fit check, not a consulting workshop or tailored professional advice.</p></div><div className="r-problem-grid">{[['01','Describe the friction','Share one recurring operational issue at a high level.'],['02','Talk through the fit','We discuss the workflow, its boundaries and the next decision.'],['03','Agree the next step','Any paid work has a written scope and fee before it begins.']].map(x=><div key={x[0]}><span className="r-number">{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Section></div>}

export function FounderIntro({homepage=false}){if(homepage)return <Section className="r-origin" id="home-team"><div className="r-origin-grid"><div><Eyebrow>The team behind Heutrix</Eyebrow><h2>We have seen operational problems from both sides.</h2></div><div><p className="r-lead">Heutrix grew from first-hand experience inside disability services and from the work of designing, delivering and building systems that improve how organisations operate.</p><p className="r-lead">Our four founders bring together provider operations, workflow implementation, project delivery, analytics and engineering. Together, that gives Heutrix the ability to understand the operational problem first, determine what actually needs to change, and then carry that improvement through to implementation.</p><a className="r-text-link" href="/about">About Heutrix <Arrow/></a></div></div><div className="r-problem-grid home-four-grid home-founders">{homeCapabilities.map(([name,summary])=><div key={name}><h3>{name}</h3><p>{summary}</p></div>)}</div></Section>;return <Section className="r-origin"><div className="r-origin-grid"><div><Eyebrow>Why Heutrix exists</Eyebrow><h2>Better workflows begin<br/>with lived experience.</h2></div><div><p className="r-lead">Heutrix grew from first-hand experience running a disability and allied health services organisation.</p><p>We brought that operational experience together with project delivery, workflow implementation, data and engineering to help teams carry work through—from the first action to a clear handover.</p><a className="r-text-link" href="/about">Read the Heutrix story <Arrow/></a></div></div></Section>}
const deliveryStories=[
 {label:'Worker onboarding',title:'An invitation is only the beginning.',before:'Creating a user account could be mistaken for completed onboarding.',after:'A possible workflow checks accepted access, appropriate permissions and a clear handover.',steps:['Create access','Send invitation','Check acceptance','Prepare handover'],caseIndex:0},
 {label:'Payment reminders',title:'Put the next action in the reminder.',before:'A generic reminder still left workers searching for the correct file, tab and instructions.',after:'An approved information location, direct link and timely reminder can give workers a clear place to act.',steps:['Prepare workbook','Provide direct link','Send reminder','Guide completion'],caseIndex:1},
 {label:'Action follow-up',title:'Give each action somewhere to go.',before:'Follow-up actions could get lost in meeting notes or broad recommendations.',after:'A shared follow-up path can show actions, owners, due dates and review.',steps:['Record action','Assign owner','Set due date','Review and close'],caseIndex:2}
];
export function DeliveryStory(){const [selected,setSelected]=useState(0);const story=deliveryStories[selected];return <Section className="r-delivery-story"><div className="r-section-heading"><div><Eyebrow>Inside the work</Eyebrow><h2>The difference is<br/>in the follow-through.</h2></div><p>Explore three possible improvements to everyday operational handovers.</p></div><div className="r-story-switch" aria-label="Explore a delivery story">{deliveryStories.map((s,i)=><button key={s.label} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{s.label}</button>)}</div><div className="r-story-panel" aria-live="polite"><h3>{story.title}</h3><ol className="r-story-path">{story.steps.map((step,i)=><li key={step}><span>0{i+1}</span><strong>{step}</strong>{i<3&&<ArrowRight aria-hidden="true"/>}</li>)}</ol><div className="r-story-change"><div><span className="r-story-label">The friction</span><p>{story.before}</p></div><div><span className="r-story-label">The change</span><p>{story.after}</p></div></div><a className="r-text-link" href={'/case-studies/'+cases[story.caseIndex].slug}>Explore this workflow <Arrow/></a><p className="r-small r-story-caption">Illustrative approach. Agree the scope, responsibilities and checks for your organisation.</p></div></Section>}
export function RefinedAbout(){return <div className="r-page">
<Section className="r-page-hero"><Eyebrow>The Heutrix story</Eyebrow><h1>We started inside<br/><span>the work.</span></h1><p className="r-lead">Heutrix grew from first-hand experience running a disability and allied health services organisation—and a practical question: how can the work behind care run more clearly?</p><div className="r-origin-grid r-about-intro"><p>In provider operations, a task rarely ends with one person. An enquiry needs a next step. A new worker needs usable access. A payment query needs the right information. Between each action is a handover that someone has to carry through.</p><p>That perspective shaped Heutrix. We focus on the everyday details that make a process work: clear ownership, information people can find and a shared understanding of what “finished” means.</p></div></Section>
<Section className="r-origin"><div className="r-origin-grid"><div><Eyebrow>Experience brought together</Eyebrow><h2>From understanding<br/>the pressure to<br/>improving the process.</h2></div><div><p className="r-lead">Our founding team brings together provider administration and operations, project delivery, workflow implementation, data and analytics, and backend engineering and infrastructure.</p><p>Those experiences meet in one approach: understand the people doing the work, trace where the process becomes difficult and build an improvement the team can use.</p><p>The workflow examples explore what that could look like in practice. Worker onboarding carries through to accepted access. Reminders include a clear place to act. Follow-up actions have an owner and a review path. Each change addresses a specific point where work can stall.</p><p>Today, we help Australian disability support providers and selected allied health practices improve one workflow at a time, with the same principle that shaped Heutrix from the start: workflow first, technology second.</p></div></div></Section>
<DeliveryStory/><Section><div className="r-origin-grid"><div><Eyebrow>How the story shapes our work</Eyebrow><h2>A clearer process.<br/>A usable handover.</h2></div><div><p>We map how work happens, agree the improvement, test it with the people who use it and document how to keep it running. Sometimes the right answer is a process change. Sometimes it is a carefully scoped build.</p><p>Clinical decisions and other accountable judgements stay with the appropriate people. Scope, responsibilities and support arrangements are agreed before paid work begins.</p><a href="/#heutrix-method" className="r-text-link">See the Process <Arrow/></a></div></div></Section><FinalCta/></div>}
