/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "dark": "rgb(var(--color-dark) / <alpha-value>)",
        "body": "rgb(var(--color-body) / <alpha-value>)",
        "action": "rgb(var(--color-action) / <alpha-value>)",
        "action-hover": "rgb(var(--color-action-hover) / <alpha-value>)",
        "accent": "rgb(var(--color-accent) / <alpha-value>)",
        "highlight": "rgb(var(--color-highlight) / <alpha-value>)",
        "page": "rgb(var(--color-page) / <alpha-value>)",
        "card": "rgb(var(--color-card) / <alpha-value>)",
        "border": "rgb(var(--color-border) / <alpha-value>)",
        "muted": "rgb(var(--color-muted) / <alpha-value>)",
        "dark-link": "rgb(var(--color-dark-link) / <alpha-value>)",
        "dark-text": "rgb(var(--color-dark-text) / <alpha-value>)",
        "success": "rgb(var(--color-success) / <alpha-value>)",
        "success-surface": "rgb(var(--color-success-surface) / <alpha-value>)",
        "warning": "rgb(var(--color-warning) / <alpha-value>)",
        "warning-surface": "rgb(var(--color-warning-surface) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "error-surface": "rgb(var(--color-error-surface) / <alpha-value>)",
        "info": "rgb(var(--color-info) / <alpha-value>)",
        "info-surface": "rgb(var(--color-info-surface) / <alpha-value>)",
        "primary": "rgb(var(--color-dark) / <alpha-value>)",
        "primary-container": "rgb(var(--color-dark) / <alpha-value>)",
        "on-primary": "rgb(var(--color-card) / <alpha-value>)",
        "secondary": "rgb(var(--color-action) / <alpha-value>)",
        "on-secondary": "rgb(var(--color-card) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-highlight) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-action) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--color-dark-link) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--color-highlight) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--color-dark) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-action) / <alpha-value>)",
        "tertiary": "rgb(var(--color-dark) / <alpha-value>)",
        "tertiary-container": "rgb(var(--color-dark) / <alpha-value>)",
        "on-tertiary": "rgb(var(--color-card) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--color-dark-link) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-highlight) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--color-dark-link) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--color-dark) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-action) / <alpha-value>)",
        "background": "rgb(var(--color-page) / <alpha-value>)",
        "on-background": "rgb(var(--color-body) / <alpha-value>)",
        "surface": "rgb(var(--color-page) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-page) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-border) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-card) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-highlight) / <alpha-value>)",
        "surface-container": "rgb(var(--color-highlight) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-highlight) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-border) / <alpha-value>)",
        "surface-variant": "rgb(var(--color-border) / <alpha-value>)",
        "surface-tint": "rgb(var(--color-body) / <alpha-value>)",
        "on-surface": "rgb(var(--color-body) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-body) / <alpha-value>)",
        "inverse-surface": "rgb(var(--color-dark) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--color-dark-text) / <alpha-value>)",
        "outline": "rgb(var(--color-muted) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-border) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-dark-text) / <alpha-value>)",
        "inverse-primary": "rgb(var(--color-dark-text) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-highlight) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--color-border) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--color-dark) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--color-body) / <alpha-value>)",
        "on-error": "rgb(var(--color-card) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-surface) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-error) / <alpha-value>)"
},
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "xs": "4px",
        "lg": "24px",
        "xl": "40px",
        "xxl": "64px",
        "container-max": "1280px",
        "base": "4px",
        "gutter": "24px",
        "sm": "8px",
        "md": "16px"
      },
      "fontFamily": {
        "body-md": ["Inter Variable", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans Variable", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans Variable", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans Variable", "sans-serif"],
        "label-sm": ["Inter Variable", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans Variable", "sans-serif"],
        "body-lg": ["Inter Variable", "sans-serif"],
        "body-sm": ["Inter Variable", "sans-serif"],
        "label-md": ["Inter Variable", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "0", "fontWeight": "700"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["30px", {"lineHeight": "38px", "letterSpacing": "0", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "0", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
